spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/profane_text_service
    username: anujk2276
    password: abcxyz
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

#  flyway:
#    locations: classpath:db/migration
#    enabled: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    ignore-migration-patterns: "*:missing"
    out-of-order: true
server:
  port: 8081
